"""
Django settings for orgona project.

Generated by 'django-admin startproject' using Django 5.1.2 (adapté à votre version).
Pour plus d'informations : 
https://docs.djangoproject.com/en/5.1/topics/settings/
"""

import os
from pathlib import Path
from decouple import config  # pip install python-decouple

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-^**obapb!s$1e^mf4#it7fd*6drrp%ol6lw)#03r-ynpu&4_v5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Vos apps
    'accounts',
    'contacts',
    'core',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orgona.urls'

# ---------- TEMPLATES : dossier global + app_dirs ----------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # Dossier global "templates" à la racine du projet
        'APP_DIRS': True,                   # Cherche aussi dans templates/ de chaque app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Pour utiliser {{ MEDIA_URL }} dans les templates
            ],
        },
    },
]

WSGI_APPLICATION = 'orgona.wsgi.application'

# ---------- DATABASE : PostgreSQL ----------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='orgona_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Password validation (inchangé)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'fr-fr'   # Modifié en français
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------- FICHIERS STATIQUES (CSS, JS, assets) ----------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']   # Dossier global "static" à la racine
STATIC_ROOT = BASE_DIR / 'staticfiles'     # Dossier de collecte pour production (python manage.py collectstatic)

# ---------- FICHIERS MÉDIAS (images, fichiers uploadés) ----------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Type de champ ID par défaut (Django 3.2+)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'